### ISSUE TITLE
VSCode + Remote Containers not working

### ISSUE THREAD

**Issue by apopaa** [bowmanjd/docker-wsl#3]
Do you have any idea how to fix this issue, with this error message:
"unable to prepare context: path "d:foobar.devcontainer" not found"

Somebody posted this question to your article, and then answered it themselves, but didn't quite clarify how. They just said "the files, which should be opened inside the devcontainer must already lie in WSL space". What files? What space?

Thank you.

**Comment by apopaa** [comment]
Nvm, I've figured it out. He meant that the folder you want to open in a container in VS Code has to reside in the Linux filesystem (/home), not in the Windows filesystem (/mnt). Once I set my project's location to a directory in the Linux filesystem (eg /home/user/my_project), and not in the Windows filesystem (eg /mnt/d/my_project), opening project files in container worked for me too. Thx.

**Comment by bowmanjd** [comment]
Glad you figured it out! Thanks for posting this.
